import React from "react"
import "./globals.css";
import { Playfair_Display } from "next/font/google"



const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
})

export const metadata = {
  title: "JustLiv",
  description: "Generated by create next app",
  icons: {
    icon:"/favicon.png", 
  },
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
